const autoCompleteList = [
    // Keywords
    { label: "auto", type: "keyword", detail: "Specifies automatic storage duration" },
    { label: "break", type: "keyword", detail: "Exits from the nearest enclosing loop or switch statement" },
    { label: "case", type: "keyword", detail: "Labels a statement that is a switch case" },
    { label: "const", type: "keyword", detail: "Declares a constant" },
    { label: "continue", type: "keyword", detail: "Skips the current iteration of a loop and continues with the next iteration" },
    { label: "default", type: "keyword", detail: "Labels the default block in a switch statement" },
    { label: "do", type: "keyword", detail: "Starts a do-while loop" },
    { label: "else", type: "keyword", detail: "Starts a block of statements to be executed if the expression in the if statement is false" },
    { label: "extern", type: "keyword", detail: "Declares a variable or function and specifies that it has external linkage" },
    { label: "for", type: "keyword", detail: "Starts a for loop" },
    { label: "goto", type: "keyword", detail: "Transfers control to the labeled statement" },
    { label: "if", type: "keyword", detail: "Starts a block of statements to be executed if a specified condition is true" },
    { label: "register", type: "keyword", detail: "Specifies that a variable is to be stored in a machine register" },
    { label: "return", type: "keyword", detail: "Exits from the current function and returns a value" },
    { label: "sizeof", type: "keyword", detail: "Returns the size of a type or variable" },
    { label: "static", type: "keyword", detail: "Declares a static variable or function" },
    { label: "switch", type: "keyword", detail: "Starts a switch statement" },
    { label: "typedef", type: "keyword", detail: "Declares a typedef name" },
    { label: "volatile", type: "keyword", detail: "Specifies that a variable may be changed unexpectedly" },
    { label: "while", type: "keyword", detail: "Starts a while loop" },
    { label: "#include", type: "keyword", detail: "Includes a header file" },


    // Data Types
    { label: "char", type: "type", detail: "Character data type" },
    { label: "int", type: "type", detail: "Integer data type" },
    { label: "float", type: "type", detail: "Floating-point data type" },
    { label: "double", type: "type", detail: "Double-precision floating-point data type" },
    { label: "void", type: "type", detail: "Empty data type (used for functions that do not return a value)" },
    { label: "short", type: "type", detail: "Short integer data type" },
    { label: "long", type: "type", detail: "Long integer data type" },
    { label: "signed", type: "type", detail: "Signed integer data type" },
    { label: "unsigned", type: "type", detail: "Unsigned integer data type" },
    { label: "struct", type: "type", detail: "Structure data type" },
    { label: "enum", type: "type", detail: "Enumeration data type" },
    { label: "union", type: "type", detail: "Union data type" },


    // Standard Library Functions (a subset)
    { label: "printf", type: "function", detail: "Prints formatted output" },
    { label: "scanf", type: "function", detail: "Reads formatted input" },
    { label: "malloc", type: "function", detail: "Allocates memory dynamically" },
    { label: "free", type: "function", detail: "Frees memory allocated by malloc" },
    { label: "strcpy", type: "function", detail: "Copies a string" },
    { label: "strlen", type: "function", detail: "Returns the length of a string" },
    { label: "strcmp", type: "function", detail: "Compares two strings" },
    { label: "pow", type: "function", detail: "Raises a number to a power" },
    { label: "sqrt", type: "function", detail: "Returns the square root of a number" },
    { label: "time", type: "function", detail: "Returns the current calendar time" },
    { label: "rand", type: "function", detail: "Generates a pseudo-random number" },
    { label: "isalpha", type: "function", detail: "Checks if a character is alphabetic" },
    { label: "isdigit", type: "function", detail: "Checks if a character is a digit" },
    { label: "getpixel", type: "function", detail: "Returns the color of a pixel" },
    { label: "putpixel", type: "function", detail: "Sets the color of a pixel" },
    { label: "circle", type: "function", detail: "Draws a circle" },
    { label: "line", type: "function", detail: "Draws a line" },
    { label: "arc", type: "function", detail: "Draws an arc" },
    { label: "ellipse", type: "function", detail: "Draws an ellipse" },
    { label: "fopen", type: "function", detail: "Opens a file" },
    { label: "fclose", type: "function", detail: "Closes a file" },
    { label: "fgetc", type: "function", detail: "Reads a character from a file" },
    { label: "fputc", type: "function", detail: "Writes a character to a file" },
    { label: "fgets", type: "function", detail: "Reads a string from a file" },
    { label: "fputs", type: "function", detail: "Writes a string to a file" },
    { label: "feof", type: "function", detail: "Checks for end-of-file" },
    { label: "fseek", type: "function", detail: "Moves the file pointer" },
    { label: "ftell", type: "function", detail: "Returns the current file pointer position" },
    { label: "rewind", type: "function", detail: "Moves the file pointer to the beginning of the file" },
    { label: "remove", type: "function", detail: "Deletes a file" },
    { label: "rename", type: "function", detail: "Renames a file" },
    { label: "abs", type: "function", detail: "Returns the absolute value of an integer" },
    { label: "labs", type: "function", detail: "Returns the absolute value of a long integer" },
    { label: "fabs", type: "function", detail: "Returns the absolute value of a floating-point number" },
    { label: "exit", type: "function", detail: "Terminates the program" },
    { label: "assert", type: "function", detail: "Checks an expression and terminates the program if it is false" },
    { label: "errno", type: "function", detail: "Returns the error number" },
    { label: "setjmp", type: "function", detail: "Jumps to a point in the program" },
    { label: "longjmp", type: "function", detail: "Jumps back to the point set by setjmp" },
    { label: "signal", type: "function", detail: "Sets a signal handler" },
    { label: "raise", type: "function", detail: "Raises a signal" },
    { label: "va_start", type: "function", detail: "Initializes a variable argument list" },
    { label: "va_arg", type: "function", detail: "Retrieves the next argument in a variable argument list" },
    { label: "va_end", type: "function", detail: "Cleans up the variable argument list" },
    { label: "memcpy", type: "function", detail: "Copies a block of memory" },
    { label: "memmove", type: "function", detail: "Moves a block of memory" },
    { label: "memcmp", type: "function", detail: "Compares two blocks of memory" },
    { label: "memset", type: "function", detail: "Sets a block of memory to a specified value" },
    { label: "drawpoly", type: "function", detail: "Draws a polygon" },
    { label: "getch", type: "function", detail: "Reads a character from the console without echoing it" },
    { label: "putch", type: "function", detail: "Writes a character to the console" },
    { label: "getchar", type: "function", detail: "Reads a character from the console" },
    { label: "putchar", type: "function", detail: "Writes a character to the console" },
    { label: "initgraph", type: "function", detail: "Initializes the graphics system" },
    { label: "closegraph", type: "function", detail: "Closes the graphics system" },
    { label: "cleardevice", type: "function", detail: "Clears the graphics screen" },
    { label: "setcolor", type: "function", detail: "Sets the current drawing color" },
    { label: "setbkcolor", type: "function", detail: "Sets the current background color" },
    { label: "setlinestyle", type: "function", detail: "Sets the line style" },
    { label: "setfillstyle", type: "function", detail: "Sets the fill pattern" },
    { label: "settextstyle", type: "function", detail: "Sets the text style" },
    { label: "outtext", type: "function", detail: "Outputs text" },
    { label: "outtextxy", type: "function", detail: "Outputs text at a specified location" },
    { label: "bar", type: "function", detail: "Draws a bar" },
    { label: "rectangle", type: "function", detail: "Draws a rectangle" },
    { label: "arc", type: "function", detail: "Draws an arc" },
    { label: "floodfill", type: "function", detail: "Flood-fills an area" },
    { label: "moveto", type: "function", detail: "Moves the current position" },
    { label: "lineto", type: "function", detail: "Draws a line to a specified point" },


    // Standard Library headers
    { label: "<stdio.h>", type: "namespace", detail: "Standard Input/Output functions" },
    { label: "<stdlib.h>", type: "namespace", detail: "Standard Library definitions" },
    { label: "<string.h>", type: "namespace", detail: "String handling functions" },
    { label: "<math.h>", type: "namespace", detail: "Math functions"},
    { label: "<time.h>", type: "namespace", detail: "Time functions" },
    { label: "<ctype.h>", type: "namespace", detail: "Character handling functions" },
    { label: "<conio.h>", type: "namespace", detail: "Console input/output functions" },
    { label: "<graphics.h>", type: "namespace", detail: "Graphics functions" },
    { label: "<dos.h>", type: "namespace", detail: "DOS functions" },
    { label: "<assert.h>", type: "namespace", detail: "Program assertion functions" },
    { label: "<errno.h>", type: "namespace", detail: "Error number definitions" },
    { label: "<locale.h>", type: "namespace", detail: "Localization functions" },
    { label: "<setjmp.h>", type: "namespace", detail: "Non-local jumps" },
    { label: "<signal.h>", type: "namespace", detail: "Signal handling functions" },
    { label: "<stdarg.h>", type: "namespace", detail: "Variable arguments handling functions" },
    { label: "<stddef.h>", type: "namespace", detail: "Standard definitions" },
    { label: "<alloc.h>", type: "namespace", detail: "Memory allocation functions" },
    { label: "<varargs.h>", type: "namespace", detail: "Variable arguments handling functions" },
    { label: "<bios.h>", type: "namespace", detail: "BIOS functions" },
    { label: "<direct.h>", type: "namespace", detail: "Directory handling functions" },


    // Additional types and macros
    { label: "NULL", type: "constant", detail: "Null pointer constant" },
    { label: "EOF", type: "constant", detail: "End-of-file indicator" },
    { label: "true", type: "constant", detail: "Boolean true value" },
    { label: "false", type: "constant", detail: "Boolean false value" },
    { label: "DETECT", type: "constant", detail: "Graphics mode detection constant" },
    { label: "VGA", type: "constant", detail: "VGA graphics mode constant" },
    { label: "HGC", type: "constant", detail: "Hercules graphics mode constant" },
    { label: "CGA", type: "constant", detail: "CGA graphics mode constant" },
    { label: "EGAVGA", type: "constant", detail: "EGA/VGA graphics mode constant" },
    { label: "BLACK", type: "constant", detail: "Color constant for black" },
    { label: "BLUE", type: "constant", detail: "Color constant for blue" },
    { label: "GREEN", type: "constant", detail: "Color constant for green" },
    { label: "CYAN", type: "constant", detail: "Color constant for cyan" },
    { label: "RED", type: "constant", detail: "Color constant for red" },
    { label: "MAGENTA", type: "constant", detail: "Color constant for magenta" },
    { label: "BROWN", type: "constant", detail: "Color constant for brown" },
    { label: "LIGHTGRAY", type: "constant", detail: "Color constant for light gray" },
    { label: "DARKGRAY", type: "constant", detail: "Color constant for dark gray" },
    { label: "LIGHTBLUE", type: "constant", detail: "Color constant for light blue" },
    { label: "LIGHTGREEN", type: "constant", detail: "Color constant for light green" },
    { label: "LIGHTCYAN", type: "constant", detail: "Color constant for light cyan" },
    { label: "LIGHTRED", type: "constant", detail: "Color constant for light red" },
    { label: "LIGHTMAGENTA", type: "constant", detail: "Color constant for light magenta" },
    { label: "YELLOW", type: "constant", detail: "Color constant for yellow" },
    { label: "WHITE", type: "constant", detail: "Color constant for white" },
    { label: "SOLID_LINE", type: "constant", detail: "Line style constant for solid line" },
    { label: "DOTTED_LINE", type: "constant", detail: "Line style constant for dotted line" },
    { label: "CENTER_LINE", type: "constant", detail: "Line style constant for center line" },
    { label: "DASHED_LINE", type: "constant", detail: "Line style constant for dashed line" },
    { label: "USER_FILL", type: "constant", detail: "Fill style constant for user-defined fill" },
    { label: "EMPTY_FILL", type: "constant", detail: "Fill style constant for empty fill" },
    { label: "SOLID_FILL", type: "constant", detail: "Fill style constant for solid fill" },
    { label: "LINE_FILL", type: "constant", detail: "Fill style constant for line fill" },
    { label: "LTSLASH_FILL", type: "constant", detail: "Fill style constant for left slash fill" },
];

export default autoCompleteList;