# Generated by Django 5.0.3 on 2024-04-02 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(blank=True, null=True)),
                ('password', models.CharField()),
                ('spanish_preference', models.BooleanField()),
                ('active', models.BooleanField()),
                ('dark_mode', models.BooleanField()),
                ('level', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.FloatField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.ranking')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.users')),
            ],
        ),
    ]
