# Generated by Django 5.0.3 on 2024-04-14 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive', '0002_alter_comments_content_alter_comments_problem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.CharField(verbose_name=512),
        ),
        migrations.AlterField(
            model_name='comments',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitive.codeproblem'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
