# Generated by Django 5.0.3 on 2024-04-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive', '0003_alter_comments_content_alter_comments_problem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.CharField(max_length=512),
        ),
    ]
