# Generated by Django 5.0.3 on 2024-06-07 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_topic', to='course.topics'),
        ),
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_unit', to='course.units'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='units',
            name='level',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
