# Generated by Django 5.0.3 on 2024-05-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='content',
            field=models.TextField(),
        ),
    ]
