# Generated by Django 5.0.3 on 2024-06-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_user_topic_user_unit_alter_topics_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='topic',
        ),
    ]
