# Generated by Django 5.0.3 on 2024-06-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_user_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='level',
        ),
    ]
