# Generated by Django 5.0.3 on 2024-06-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_topics_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='units',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
