# Generated by Django 5.0.3 on 2024-06-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_topics_level_units_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='units',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='units',
            name='level',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='name',
            field=models.TextField(),
        ),
    ]
